### PR TITLE
feat(storage): allow .ics (text/calendar) file uploads

### LINKED ISSUE #6159: Allow users to upload .ics files
**Is your feature request related to a problem? Please describe.**
Yes, the admin of a Space wants to upload an .ics file to allow her community to download the event information so they can add it to their personal calendar.

**Describe the solution you'd like**
Where we support uploading files, to also support ics as a file type. 

**Describe alternatives you've considered**
Asking them to download it from the events calendar, but this needs quite some instructions, whereas uploading it in a CTA post or as a reference is much cleaner.

**Additional context**
Hopefully this is a one time change, allowing ics everywhere, but if not, these are the crucial locations:
- [ ] Post - additional content: CTA button
- [ ] Post - reference
- [ ] Post - reactions: links & files
- [ ] About this Space - references
- [ ] Community guidelines - references

### PR DESCRIPTION
**Pull request by valentinyanakiev**
## Summary

Adds the iCalendar MIME type (`text/calendar`, `.ics`) to the server-side document upload allowlist so Space admins can upload `.ics` files wherever document upload is supported — post CTA buttons, post references, post reactions (links & files), About-this-Space references, and community-guidelines references.

Closes alkem-io/server#6159

## Root cause

Uploaded documents are validated against a per-bucket MIME allowlist. New storage buckets default to `DEFAULT_ALLOWED_MIME_TYPES`, which is `Object.values(MimeFileType)` — the union of `MimeTypeVisual` + `MimeTypeDocument`. `text/calendar` was simply absent from that enum, so `.ics` uploads were rejected with a `ValidationException` everywhere.

## Fix

- **Enum (single source of truth):** add `ICS = 'text/calendar'` to `MimeTypeDocument` (`src/common/enums/mime.file.type.document.ts`). This flows automatically into `DEFAULT_ALLOWED_MIME_TYPES`, so every newly-created bucket accepts `.ics`. Placed next to the other plain-text type (`CSV`) and follows the existing naming/casing.
- **Backfill migration:** `1782300000000-AddIcsMimeType` appends `text/calendar` to existing `storage_bucket` rows that already allow documents (using `application/pdf` as the canonical marker), guarded against duplicates, with a matching `down()`. This mirrors the established `1770909862763-AddHeicHeifMimeTypes` precedent — existing buckets persist their allowlist as a frozen comma-separated string column, so without the backfill only new buckets would accept `.ics`.
- **Schema:** regenerated `schema.graphql` — additive `ICS` value on the `MimeType` enum (non-breaking).

No new validation mechanism was introduced; the change rides the existing allowlist exactly like `pdf`/`csv`.

## Regression test

`src/common/enums/mime.file.type.document.spec.ts` asserts `MimeTypeDocument.ICS === 'text/calendar'`, that it is surfaced via the combined `MimeFileType`, and that `DEFAULT_ALLOWED_MIME_TYPES` contains `text/calendar` (i.e. new buckets accept it).

## Gates

- `pnpm test` — green (6922 passed, +3 new)
- `pnpm lint` (tsc --noEmit + biome) — clean
- `pnpm build` — clean
- `pnpm run schema:print && schema:sort` — only the additive `ICS` enum value

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **New Features**
  * Added support for iCalendar (`ICS`) as an allowed MIME type.
  * Updated default allowed file types so calendar files can be uploaded and stored.
* **Bug Fixes**
  * Updated existing storage bucket settings to include `text/calendar` where appropriate.
* **Tests**
  * Added coverage to verify the new `ICS` MIME type mapping and default allowed MIME type list.
  * Improved resolver test inputs to use a readable stream for document uploads.

### CODE REVIEW

**Comment by valentinyanakiev** [comment]
Pushed `f83883c7b` to fix the failing `test` job — a **pre-existing flake unrelated to the `.ics` change**, surfaced by this PR's run.

**Symptom:** `callout.resolver.mutations.spec.ts > importCollaboraDocument` → `TypeError: stream.on is not a function` (2 tests), plus an unhandled `stream.destroy is not a function` mis-attributed to `lookup.resolver.my.privileges.fields.spec.ts`.

**Root cause:** both specs originate from #6187 and pass `createReadStream: () => ({})`, relying on the file-scoped `vi.mock` of `streamToBuffer`. Under the CI vitest config (`pool: 'threads'`, `isolate: false`) the shared module cache lets a prior spec's *real* `@common/utils/file.util` win, so the resolver runs the real `streamToBuffer` against a non-stream. The throw rejects the call, and the executor's `setTimeout` is never cleared → it later fires `stream.destroy()` on `{}`, producing the unhandled error in whatever spec runs next in that thread. Passes in isolation (mock applies), fails in the full suite.

**Fix:** feed a real `Readable` (`Readable.from(Buffer.from('test'))`) so the test is correct whether the mock applies or the real `streamToBuffer` runs — the timer is cleared on `end`, no handle leaks. Existing `vi.mock` kept as belt-and-suspenders.

Verified locally: full `pnpm test:ci:no:coverage` → **6922 passed, 7 skipped, 0 failed**, no unhandled errors.
